{
    "storageDir":"s\/",
    "deletionEnabled":true,
    "passwordProtected":false,
    "passwordMD5Encrypted":"",
    "loadStatsAsynchronous":true,
    "sortAlphabetically":false,
    "limitDisplayedShorten":0,
    "publicCookies":false,
    "choosableShorten":true
}